const questions = [
  {
    id: "sofa",
    text: "Sofa is full shrinked and wrapped in blankets:",
    options: ["YES", "NO", "NO SOFA"],
    itemName: "Sofa",
  },
  {
    id: "mattress",
    text: "Mattress in box, full shrinked and wrapped in blankets:",
    options: ["YES", "NO", "NO MATTRESS"],
    itemName: "Mattress",
  },
  {
    id: "wardrobe",
    text: "Wardrobe with only clothes/pillows inside:",
    options: ["YES", "NO", "NO WARDROBE"],
    itemName: "Wardrobe",
  },
  {
    id: "tvbox",
    text: "TV Box with only TV or Paintings inside:",
    options: ["YES", "NO", "NO TV BOX"],
    itemName: "TV Box",
  },
  {
    id: "paintings",
    text: "Paintings or glass in TV Box are separated from each other by boxes:",
    options: ["YES", "NO", "NO PAINTING/GLASS"],
    itemName: "Paintings/Glass",
  },
  {
    id: "corners",
    text: "Corners/Cardboard are placed on all furniture where required:",
    options: ["YES", "NO"],
    itemName: "Corners/Cardboard",
  },
  {
    id: "wooden",
    text: "Wooden items are full wrapped in blankets:",
    options: ["YES", "NO", "NO WOODEN PARTS"],
    itemName: "Wooden Items",
  },
  {
    id: "leather",
    text: "Leather items are wrapped in blankets without shrink:",
    options: ["YES", "NO", "NO LEATHER ITEMS"],
    itemName: "Leather Items",
  },
  {
    id: "suitcases",
    text: "Suitcases are full shrinked:",
    options: ["YES", "NO", "NO SUITCASES"],
    itemName: "Suitcases",
  },
  {
    id: "lamps",
    text: "Lamps in Boxes/Bubble wrap/wrapped in blankets:",
    options: ["YES", "NO", "NO LAMPS"],
    itemName: "Lamps",
  },
  {
    id: "bikes",
    text: "Bicycle/Peloton is full wrapped in blankets:",
    options: ["YES", "NO", "NO BIKES"],
    itemName: "Bicycle/Peloton",
  },
  {
    id: "rugs",
    text: "Rugs/Carpets are full shrinked:",
    options: ["YES", "NO", "NO RUGS"],
    itemName: "Rugs/Carpets",
  },
  {
    id: "hardware",
    text: "Hardware Box:",
    options: ["YES", "NO"],
    itemName: "Hardware Box",
  },
];

const defaultValuesConfig = {
  sofa: "NO SOFA",
  mattress: "NO MATTRESS",
  wardrobe: "NO WARDROBE",
  tvbox: "NO TV BOX",
  paintings: "NO PAINTING/GLASS",
  corners: "YES",
  wooden: "YES",
  leather: "NO LEATHER ITEMS",
  suitcases: "NO SUITCASES",
  lamps: "NO LAMPS",
  bikes: "NO BIKES",
  rugs: "NO RUGS",
  hardware: "YES",
};

const keywordMap = {
  sofa: [
    "sofa",
    "couch",
    "ottoman",
    "loveseat",
    "settee",
    "sectional",
    "sofa bed",
  ],
  mattress: ["mattress", "box spring", "boxspring"],
  wardrobe: ["wardrobe", "wardrobe box", "armoire"],
  tvbox: ["tv box", "tvbox"],
  paintings: ["painting", "glass", "picture", "art", "canvas", "mirror"],
  leather: ["leather"],
  suitcases: ["suitcase"],
  lamps: ["lamp"],
  bikes: ["bike", "bicycle", "peloton", "exercise bike"],
  rugs: ["rug", "carpet"],
  hardware: ["hardware", "hardware box"],
};

const attentionFieldIds = []; // "wooden" removed

const sheetDataInputIds = [
  "sheetWarehouse",
  "sheetAddress",
  "sheetPallets",
  "sheetItems",
  "sheetEmployeeName",
  "sheetBingoStatusOK",
  "sheetBingoDetails",
  "sheetMatTV",
  "sheetMatWR",
  "sheetMatBL",
  "useLoadingDock",
];

const ALL_INPUT_IDS_FOR_RESET_STATIC = [
  "clientName",
  "job",
  "cuFt",
  "generalComments",
  "rating",
  "pdfFile",
  "sheetWarehouse",
  "sheetAddress",
  "sheetPallets",
  "sheetItems",
  "sheetEmployeeName",
  "sheetBingoStatusOK",
  "sheetBingoDetails",
  "sheetMatTV",
  "sheetMatWR",
  "sheetMatBL",
  "useLoadingDock",
  "enablePhotoCommentsToggle",
  "spreadsheetIdInput",
  "sheetNameInput",
  "startRowInput",
];
